load(
    "@rules_apple_line//apple:objc_static_framework.bzl",
    "objc_static_framework",
)

objc_static_framework(
    name = "PureObjC",
    srcs = glob([
        "**/*.m",
    ]),
    hdrs = glob([
        "**/*.h",
    ]),
)
